apiVersion: v1
kind: Secret 
metadata:
  name: profile-credit-sync-keycloak-creds
  namespace: sandbox
stringData:
  PROFILE_CREDIT_SYNC_KEYCLOAK_USERNAME: "<username>"
  PROFILE_CREDIT_SYNC_KEYCLOAK_PASSWORD: "<password>"
