apiVersion: v1
kind: ConfigMap
metadata:
  name: sandbox-worker-config
  namespace: sandbox
data:
  WORKER_CPU_NOTEBOOK_IMAGE: "registry.analytics.cbr-iisc.ac.in/tgdex/demo-notebook-file:mahaagx"
  WORKER_GPU_NOTEBOOK_IMAGE: "registry.analytics.cbr-iisc.ac.in/tgdex/ai-sandbox-cpu-notebook:latest"
  WORKER_INIT_CONTAINER_IMAGE: "registry.analytics.cbr-iisc.ac.in/tgdex/ai-sandbox-gpu-notebook:latest"
  WORKER_IMAGE_PULL_ENABLED: "true"
  WORKER_ECR_SECRET_NAME: "registry-cred"
  WORKER_GPU_NODE_INSTANCE_TYPE: "g4dn.xlarge"
  WORKER_CPU_NODE_INSTANCE_TYPES: "t3a.2xlarge,c5a.4xlarge"
