apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-worker
  namespace: sandbox
  labels:
    app: sandbox-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-worker
  template:
    metadata:
      labels:
        app: sandbox-worker
    spec:
      serviceAccountName: notebook-manager-sa 
      imagePullSecrets:
      - name: tgdex-registry-cred
      containers:
      - name: worker
        image: ghcr.io/datakaveri/tgdex-sandbox-connect-worker:tgdex-1.0.0
        envFrom:
        - configMapRef:
            name: sandbox-worker-config
        env:
        - name: WORKER_RUNTIME_CONFIG_PATH
          value: "/etc/sandbox-worker/runtime/runtime-config.yaml"
        - name: WORKER_POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: database-creds 
              key: POSTGRES_URL
        - name: WORKER_KUBE_CONFIG_MODE
          value: "cluster"
        - name: WORKER_MAX_CONCURRENT_WORKER
          value: "5"  
        - name: WORKER_S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: s3-creds 
              key: S3_ENDPOINT
        - name: WORKER_S3_REGION
          valueFrom:
            secretKeyRef:
              name: s3-creds 
              key: S3_REGION
        - name: WORKER_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-creds 
              key: S3_ACCESS_KEY
        - name: WORKER_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-creds 
              key: S3_SECRET_KEY
        - name: WORKER_S3_TEMPLATE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: s3-creds 
              key: S3_TEMPLATE_BUCKET_NAME
        - name: WORKER_STORAGE_CLASS_NAME
          value: "ebs-csi-storage-class"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: runtime-config
          mountPath: /etc/sandbox-worker/runtime
          readOnly: true
      volumes:
      - name: runtime-config
        configMap:
          name: sandbox-worker-runtime-config
          items:
          - key: runtime-config.yaml
            path: runtime-config.yaml
---
apiVersion: v1
kind: Service 
metadata:
  name: sandbox-worker-svc
  namespace: sandbox
spec:
  selector:
    app: sandbox-worker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
