apiVersion: batch/v1
kind: CronJob
metadata:
  name: slot-lifecycle
  namespace: sandbox
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: slot-lifecycle
            type: cron
        spec:
          serviceAccountName: notebook-manager-sa
          imagePullSecrets:
            - name: tgdex-registry-cred
          containers:
            - name: slot-lifecycle
              image: ghcr.io/datakaveri/tgdex-slot-lifecycle-cron:tgdex-1.0.0
              env:
                - name: SLOT_LIFECYCLE_POSTGRES_URL
                  valueFrom:
                    secretKeyRef:
                      name: database-creds
                      key: POSTGRES_URL
              envFrom:
                - configMapRef:
                    name: slot-lifecycle-config
              resources:
                limits:
                  memory: "1Gi"
                  cpu: "500m"
                requests:
                  memory: "256Mi"
                  cpu: "100m"
          restartPolicy: Never

