apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook-config
  namespace: sandbox
data:
  DEFAULT_USER_ID: "00000000-0000-0000-0000-000000000000"
  DEFAULT_NAMESPACE: "00000000-0000-0000-0000-000000000000"
  DEFAULT_STORAGE_SIZE: "10Gi"
  DEFAULT_CPU_REQUEST: "1"
  DEFAULT_CPU_LIMIT: "2"
  DEFAULT_MEMORY_REQUEST: "2Gi"
  DEFAULT_MEMORY_LIMIT: "4Gi"
  DEFAULT_GPU_TYPE: "nvidia"
  DEFAULT_GPU_LIMIT: "1"
  KUBEFLOW_URL: "https://sandbox.tgdex.telangana.gov.in"
  