apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: sandbox
data:
  API_DEFAULT_CPU_STORAGE_SIZE: "10Gi"
  API_DEFAULT_GPU_STORAGE_SIZE: "50Gi"
  API_DEFAULT_CPU_REQUEST: "3.5"
  API_DEFAULT_CPU_LIMIT: "4"
  API_DEFAULT_MEMORY_REQUEST: "7.5Gi"
  API_DEFAULT_MEMORY_LIMIT: "8Gi"
  API_DEFAULT_GPU_TYPE: "nvidia.com/gpu"
  API_DEFAULT_GPU_REQUEST: "1"
  API_DEFAULT_GPU_LIMIT: "1"
  API_KUBEFLOW_URL: "https://sandbox.tgdex.telangana.gov.in"
  API_NOTEBOOK_LIST_LIMIT: "10"
  API_ADDRESS: "0.0.0.0:3000"
  API_KUBE_CONFIG_MODE: "cluster"
  API_CORS_ORIGINS: "*"
  API_KYC_ENABLED: "true"
  API_RATE_LIMIT: "80"
  API_RATE_WINDOW_SECS: "30"
  API_KEYCLOAK_URL: "https://idp.tgdex.telangana.gov.in/auth"
  API_KEYCLOAK_REALM: "tgdex"
  API_KEYCLOAK_CLIENT_ID: "angular-tgdex-client"
  API_TIMEOUT_SECS: "60"
  API_IDLE_TIMEOUT_SECS: "120"
  API_MAX_BODY_SIZE_IN_MB: "5"
  API_WRITE_TIMEOUT_SECS: "60"
  API_READ_TIMEOUT_SECS: "30"
  API_KEYCLOAK_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvkKGd9ztloOSZscVXESeBIk5marME7uPEgMQXTvxEUrb0DBLG+rSfU0xPfG0XmQnU6IELXEJaMG3L2el3lkT40RK/TZO/0XzRxFUqGivavGec7Yzu8PrbOPrD/r0b6P6syijtqndV2U00FuJZqpg2YUATq+MRL23uyeW9EiZlOEBrAH82tgRZPukwN91bAqVgwng/pxPoBS1T6NzF8kW8ul0p81IA3Y+qalfuJ+mRtGsbH6T7hewQUT6P7csRmXN+tSDtAPtwwwHHzDF8X46kkJ88IHA2WjXMZKJAU5klI/ZxFmyWnqGM53zgFFbH5MQCmOUhed7l+w/Y80f6NqyYQIDAQAB"
  API_VERSION: "v1"
  API_MAX_RUNNING_CPU: "1"
  API_MAX_RUNNING_GPU: "1"
  API_MAX_TOTAL_CPU: "6"
  API_MAX_TOTAL_GPU: "4"
  API_DEFAULT_GPU_CPU_REQUEST: "3"
  API_DEFAULT_GPU_CPU_LIMIT: "3.9"
  API_DEFAULT_GPU_MEMORY_REQUEST: "12Gi"
  API_DEFAULT_GPU_MEMORY_LIMIT: "14Gi"
  API_LOG_LEVEL: "debug"
  API_AAA_URL: "https://dx.tgdex.telangana.gov.in"
  API_CREATE_ECR_SECRET: "false"
  API_ECR_REGION: "us-east-1"
  API_ECR_REGISTRY_URL: "<your-ecr-registry-url>"
  API_ECR_SECRET_NAME: "ecr-registry-cred"
  API_OPENCOST_URL: "http://opencost.opencost:9003"
  API_KEYCLOAK_BILLING_CLIENT_ID: "frontend-client"
  # only value we can put here
  WORKER_GPU_NODE_INSTANCE_TYPE: "g4dn.xlarge"
  # multiple value we can put here
  WORKER_CPU_NODE_INSTANCE_TYPES: "t3a.2xlarge,c5a.4xlarge"
