 apiVersion: v1
 kind: Secret
 metadata:
   name: api-creds
   namespace: sandbox
 stringData:
   API_KEYCLOAK_ADMIN_USERNAME: "<username>"
   API_KEYCLOAK_ADMIN_PASSWORD: "<password>"
   API_AWS_ACCESS_KEY_ID: "<your-aws-access-key-id>"
   API_AWS_SECRET_KEY: "<your-aws-secret-key>"
