apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-refresher-config
  namespace: sandbox
data:
  SECRET_REFRESHER_SECRET_NAME: "tgdex-registry-cred"
  SECRET_REFRESHER_SECRET_NAMESPACE: "sandbox"
  SECRET_REFRESHER_ECR_REGION: "ap-south-1"
  SECRET_REFRESHER_ECR_REGISTRY_URL: "108779579607.dkr.ecr.ap-south-1.amazonaws.com"
  SECRET_REFRESHER_K8S_CONFIG_MODE: "cluster"
