apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-creator
  namespace: sandbox
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: notebook-manager-sa
          restartPolicy: Never
          containers:
          - name: secret-creator
            image: ghcr.io/datakaveri/tgdex-sandbox-connect-secret-refresher:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: secret-refresher-config
            - secretRef:
                name: ecr-creds
            resources:
              limits:
                cpu: "200m"
                memory: "128Mi"
              requests:
                cpu: "100m"
                memory: "64Mi"
