apiVersion: batch/v1
kind: Job
metadata:
  name: secret-creator-init
  namespace: sandbox
spec:
  template:
    spec:
      serviceAccountName: secret-refresher-sa
      restartPolicy: Never
      containers:
      - name: secret-creator
        image: ghcr.io/datakaveri/tgdex-sandbox-connect-secret-refresher:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: secret-refresher-config
        - secretRef:
            name: ecr-creds
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
