apiVersion: v1
kind: Secret
metadata:
  name: ecr-creds
  namespace: sandbox
type: Opaque
stringData:
  SECRET_REFRESHER_AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
  SECRET_REFRESHER_AWS_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
