// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/notebook/check-exists/{notebook_name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Checks if a notebook with the given name exists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "Check if notebook exists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notebook Name",
                        "name": "notebook_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerExistsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Error400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
                }
            }
        },
        "/v1/notebook/gpu-instance-types": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the list of available GPU node instance types with display metadata for notebook creation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "List available GPU instance types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GPUInstanceTypesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        },
        "/v1/notebook/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new notebook for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "Create notebook",
                "parameters": [
                    {
                        "description": "Notebook Create Request",
                        "name": "notebook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.NotebookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/main.Error403"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/main.Error409"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/main.Error422"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        },
        "/v1/notebook/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a notebook by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "Delete notebook",
                "parameters": [
                    {
                        "description": "Notebook Delete Request",
                        "name": "notebook_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DeleteNotebookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.Error404"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/main.Error422"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        },
        "/v1/notebook/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists all notebooks for the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "List notebooks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of notebooks to return (max 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date filter as JSON array of two date strings [start, end]",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.NotebookListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Error400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        },
        "/v1/notebook/start": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts an existing notebook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "Start notebook",
                "parameters": [
                    {
                        "description": "Notebook Start Request",
                        "name": "notebook_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.StartNotebookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.Error404"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/main.Error422"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        },
        "/v1/notebook/status/{notebook_name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets the status of a notebook",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "Get notebook status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notebook Name",
                        "name": "notebook_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.NotebookStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.Error404"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        },
        "/v1/notebook/stop": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stops a running notebook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notebook"
                ],
                "summary": "Stop notebook",
                "parameters": [
                    {
                        "description": "Notebook Stop Request",
                        "name": "notebook_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.StopNotebookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Error400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.Error404"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/main.Error422"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        },
        "/v1/profile/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a Kubeflow Profile CRD for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Create Kubeflow profile",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Error401"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/main.Error422"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/main.Error429"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.Error500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "constants.Events": {
            "type": "string",
            "enum": [
                "picked",
                "pvc-applied",
                "pvc-apply-failed",
                "pvc-created",
                "pvc-creation-failed",
                "pvc-upload-successful",
                "pvc-upload-applied",
                "pvc-upload-apply-failed",
                "pvc-upload-failed",
                "notebook-applied",
                "notebook-apply-failed"
            ],
            "x-enum-varnames": [
                "StatusPicked",
                "StatusPVCApplied",
                "StatusPVCApplyFailed",
                "StatusPVCCreated",
                "StatusPVCCreationFailed",
                "StatusPVCUploadSuccessful",
                "StatusPVCUploadApplied",
                "StatusPVCUploadApplyFailed",
                "StatusPVCUploadFailed",
                "StatusNotebookApplied",
                "StatusNotebookApplyFailed"
            ]
        },
        "main.DeleteNotebookRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "main.GPUInstanceType": {
            "description": "A single GPU instance type option with display metadata",
            "type": "object",
            "properties": {
                "instanceType": {
                    "description": "AWS instance type identifier",
                    "type": "string",
                    "example": "g4dn.xlarge"
                },
                "displayName": {
                    "description": "Display name for the card UI",
                    "type": "string",
                    "example": "Basic"
                },
                "gpuMemory": {
                    "description": "GPU memory available",
                    "type": "string",
                    "example": "16 GB"
                },
                "description": {
                    "description": "Human-readable description of the GPU",
                    "type": "string",
                    "example": "16 GB NVIDIA T4 GPU"
                },
                "sessionDuration": {
                    "description": "Maximum session duration",
                    "type": "string",
                    "example": "4h Session"
                }
            }
        },
        "main.GPUInstanceTypesResponse": {
            "description": "List of available GPU instance types with metadata",
            "type": "object",
            "properties": {
                "instanceTypes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GPUInstanceType"
                    }
                }
            }
        },
        "main.Error400": {
            "description": "Response for bad request errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.Error401": {
            "description": "Response for authentication errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.Error403": {
            "description": "Response for permission errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.Error404": {
            "description": "Response for resource not found errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.Error409": {
            "description": "Response for resource conflict errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.Error422": {
            "description": "Response for invalid request body errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.Error429": {
            "description": "Response for rate limiting errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.Error500": {
            "description": "Response for internal server errors",
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Error message",
                    "type": "string",
                    "example": "string"
                },
                "type": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "main.NotebookListResponse": {
            "type": "object",
            "properties": {
                "next_offset": {
                    "type": "integer"
                },
                "notebooks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.NotebookStatus"
                    }
                }
            }
        },
        "main.NotebookRequest": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                },
                "type": {
                    "description": "Notebook type (cpu or gpu)",
                    "type": "string"
                },
                "instanceType": {
                    "description": "GPU instance type (required when type=gpu). Must match one of the types from GET /v1/notebook/gpu-instance-types",
                    "type": "string"
                }
            }
        },
        "main.NotebookState": {
            "type": "string",
            "enum": [
                "opening",
                "running",
                "stopped",
                "failed",
                "orphaned"
            ],
            "x-enum-varnames": [
                "NotebookStateOpening",
                "NotebookStateRunning",
                "NotebookStateStopped",
                "NotebookStateFailed",
                "NotebookStateOrphaned"
            ]
        },
        "main.NotebookStatus": {
            "type": "object",
            "properties": {
                "cpuLimit": {
                    "type": "number"
                },
                "cpuRequest": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/constants.Events"
                    }
                },
                "gpuLimit": {
                    "type": "integer"
                },
                "gpuRequest": {
                    "type": "integer"
                },
                "gpuType": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "instanceType": {
                    "description": "GPU instance type selected for the notebook (null for CPU notebooks)",
                    "type": "string"
                },
                "memoryLimit": {
                    "type": "string"
                },
                "memoryRequest": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "notebookUrl": {
                    "type": "string"
                },
                "pvcName": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/main.NotebookState"
                },
                "storageSize": {
                    "type": "string"
                },
                "templateName": {
                    "type": "string"
                }
            }
        },
        "main.StartNotebookRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "main.StopNotebookRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "main.SwaggerExistsResponse": {
            "description": "Response structure for check-exists endpoint",
            "type": "object",
            "properties": {
                "exists": {
                    "description": "Whether the resource exists",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "main.SwaggerMessageResponse": {
            "description": "Standard success response structure with a message",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Success message",
                    "type": "string",
                    "example": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token authentication. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "x-extension-info-cors": "Configurable CORS origins",
    "x-extension-info-ratelimit": "100 requests per minute"
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Sandbox Connect API",
	Description:      "API for managing notebooks and profiles",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
