name: Publish TGDex Sandbox Connect Secret Refresher Image
on:
  workflow_dispatch
jobs:
  publish_secret_refresher_image:
    name: Build and Push Secret Refresher Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.USERNAME }}
          password: ${{ secrets.PAC_TOKEN }}

      - name: Build and push Secret Refresher image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/cron/secret-refresher/Dockerfile
          push: true
          tags: |
            ghcr.io/datakaveri/tgdex-sandbox-connect-secret-refresher:${{ steps.slug.outputs.sha7 }}
            ghcr.io/datakaveri/tgdex-sandbox-connect-secret-refresher:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
